name: trellis
channels:
  - defaults
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=7_kmp_llvm
  - aom=3.12.1=h7934f7d_0
  - blas=2.304=openblas
  - blas-devel=3.11.0=4_h1ea3ea9_openblas
  - brotlicffi=1.2.0.0=py310h7354ed3_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - cairo=1.18.4=h44eff21_0
  - certifi=2025.11.12=py310h06a4308_0
  - cffi=2.0.0=py310h4eded50_1
  - charset-normalizer=3.4.4=py310h06a4308_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cuda-version=12.9=3
  - dav1d=1.2.1=h5eee18b_0
  - expat=2.7.3=h7354ed3_4
  - ffmpeg=6.1.1=hecf7045_5
  - fontconfig=2.15.0=h2c49b7f_0
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - giflib=5.2.2=h5eee18b_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.2=py310ha78e65c_0
  - graphite2=1.3.14=h295c915_1
  - harfbuzz=10.2.0=hdfddeaa_1
  - icu=73.1=h6a678d5_0
  - idna=3.11=py310h06a4308_0
  - jinja2=3.1.6=py310h06a4308_0
  - jpeg=9f=h5ce9db8_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.17=heab6991_0
  - ld_impl_linux-64=2.44=h153f514_2
  - leptonica=1.82.0=hfdeec58_3
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20240116.2=cxx17_he02047a_1
  - libarchive=3.8.2=h3ec8f01_0
  - libavif=1.3.0=h3539ee5_0
  - libblas=3.11.0=4_h4a7cf45_openblas
  - libcblas=3.11.0=4_h0358290_openblas
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.14.1.1=4
  - libcurand=10.3.10.19=0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.22=h5eee18b_0
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libglib=2.84.4=h77a78f3_0
  - libgomp=15.2.0=h4751f2c_7
  - libhwloc=2.12.1=default_hf1bbc79_1000
  - libiconv=1.16=h5eee18b_3
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - liblapack=3.11.0=4_h47877c9_openblas
  - liblapacke=3.11.0=4_h6ae95b6_openblas
  - libnpp=11.8.0.86=0
  - libnsl=2.0.0=h5eee18b_0
  - libnvjpeg=11.9.0.86=0
  - libogg=1.3.5=h27cfd23_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libopenjpeg=2.5.4=hee96239_1
  - libopus=1.3.1=h5eee18b_1
  - libpng=1.6.50=h2ed474d_0
  - libprotobuf=4.25.3=hd5b35b9_1
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtheora=1.2.0=h32ad74f_1
  - libtiff=4.7.1=h029b1ac_0
  - libtorch=2.4.0=cpu_generic_h4a3044c_1
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.51.0=hb03c661_1
  - libvorbis=1.3.7=h7b6447c_0
  - libvpx=1.15.2=h4cb591d_0
  - libwebp=1.6.0=h089d785_0
  - libwebp-base=1.6.0=hb7bb969_0
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - llvm-openmp=21.1.7=h4922eb0_0
  - lz4-c=1.9.4=h6a678d5_1
  - mkl=2024.0.0=ha957f24_49657
  - mkl-include=2024.0.0=ha957f24_49657
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py310h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - nomkl=3.0=0
  - openblas=0.3.30=pthreads_h6ec200e_4
  - openh264=2.6.0=he621ea3_0
  - openjpeg=2.5.4=h4e0627c_1
  - openssl=3.6.0=h26f9b46_0
  - pcre2=10.46=hf426167_0
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h7934f7d_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pycparser=2.23=py310h06a4308_0
  - pysocks=1.7.1=py310h06a4308_1
  - python=3.10.19=h6fa692b_0
  - python_abi=3.10=2_cp310
  - pytorch-cuda=11.8=h7e8668a_6
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.3=py310h591646f_0
  - readline=8.3=hc2a1206_0
  - requests=2.32.5=py310h06a4308_1
  - setuptools=80.9.0=py310h06a4308_0
  - sleef=3.9.0=ha0421bc_0
  - sqlite=3.51.0=h2a70700_0
  - tbb=2021.13.0=h8d10470_4
  - tesseract=5.2.0=hb0d2e87_3
  - tk=8.6.15=h54e0aa7_0
  - typing_extensions=4.15.0=py310h06a4308_0
  - urllib3=2.6.1=py310h06a4308_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - addict==2.4.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.0
      - asttokens==3.0.1
      - attrs==25.4.0
      - blinker==1.9.0
      - boto3==1.42.8
      - botocore==1.42.8
      - cachetools==6.2.2
      - ccimport==0.4.4
      - click==8.3.1
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - comm==0.2.3
      - configargparse==1.7.1
      - contourpy==1.3.2
      - cumm-cu120==0.4.11
      - cycler==0.12.1
      - dash==3.3.0
      - dataclasses-json==0.6.7
      - decorator==5.2.1
      - deprecated==1.3.1
      # - diff-gaussian-rasterization==0.0.0
      - distro==1.9.0
      - easydict==1.13
      - einops==0.8.1
      - entrypoints==0.4
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - fastapi==0.122.0
      - fastjsonschema==2.21.2
      - filelock==3.19.1
      - fire==0.7.1
      # - flash-attn==2.7.4.post1
      - flask==3.1.2
      - flatbuffers==25.9.23
      - fonttools==4.61.0
      - fsspec==2025.9.0
      - genai-prices==0.0.48
      - glcontext==3.0.0
      - google-auth==2.43.0
      - google-genai==1.55.0
      - griffe==1.15.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - hydra-core==1.3.2
      - igraph==1.0.0
      - imageio==2.37.2
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.7.0
      - ipycanvas==0.14.3
      - ipyevents==2.0.4
      - ipython==8.37.0
      - ipywidgets==8.1.8
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jmespath==1.0.1
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==7.4.9
      - jupyter-core==5.9.1
      - jupyterlab-widgets==3.0.16
      - kaolin==0.18.0
      - kiwisolver==1.4.9
      - lark==1.3.1
      - lazy-loader==0.4
      - llvmlite==0.46.0
      - logfire-api==4.16.0
      - markupsafe==2.1.5
      - marshmallow==3.26.1
      - matplotlib==3.10.8
      - matplotlib-inline==0.2.1
      - moderngl==5.12.0
      - mypy-extensions==1.1.0
      - narwhals==2.13.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.3
      - ninja==1.13.0
      - numba==0.63.1
      - numpy==2.1.2
      - nvdiffrast==0.3.3
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - onnxruntime==1.23.2
      - open3d==0.19.0
      - opencv-python-headless==4.12.0.88
      - opentelemetry-api==1.39.1
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - pccm==0.4.16
      - pexpect==4.9.0
      - pillow==11.3.0
      - platformdirs==4.5.1
      - plotly==6.5.0
      - plyfile==1.1.3
      - pooch==1.8.2
      - portalocker==3.2.0
      - prompt-toolkit==3.0.52
      - protobuf==6.33.2
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybind11==3.0.1
      - pydantic==2.12.0
      - pydantic-ai-slim==1.0.17
      - pydantic-core==2.41.1
      - pydantic-graph==1.0.17
      - pygltflib==1.16.5
      - pygments==2.19.2
      - pymatting==1.1.14
      - pymeshfix==0.17.1
      - pyparsing==3.2.5
      - pyquaternion==0.9.9
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.0
      - pytz==2025.2
      - pyvista==0.46.4
      - pyzmq==27.1.0
      - referencing==0.37.0
      - regex==2025.11.3
      - rembg==2.0.69
      - retrying==1.4.2
      - rpds-py==0.30.0
      - rsa==4.9.1
      - s3transfer==0.16.0
      - safetensors==0.7.0
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - scooby==0.11.0
      - six==1.17.0
      - sniffio==1.3.1
      - spconv-cu120==2.3.6
      - stack-data==0.6.3
      - starlette==0.50.0
      - structlog==25.5.0
      - sympy==1.13.1
      - tenacity==9.1.2
      - termcolor==3.2.0
      - texttable==1.7.0
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - tokenizers==0.22.1
      # - torch==2.6.0+cu124
      # - torchvision==0.21.0+cu124
      - tornado==6.5.3
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.57.3
      - trimesh==4.10.1
      - triton==3.2.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - usd-core==25.11
      - utils3d==0.0.2
      - uvicorn==0.38.0
      - uvloop==0.22.1
      - vtk==9.5.2
      - warp-lang==1.10.1
      - watchfiles==1.1.1
      - wcwidth==0.2.14
      - websockets==15.0.1
      - werkzeug==3.1.4
      - widgetsnbextension==4.0.15
      - wrapt==2.0.1
      - xatlas==0.0.11
      - zipp==3.23.0
# prefix: /root/miniconda3/envs/trellis
